language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true

services:
  - postgresql

before_script:
  - psql -c "CREATE USER openerp WITH PASSWORD 'admin';" -U postgres
  - psql -c 'create database web_unleashed_test with owner openerp;' -U postgres

install:
  - ./.travis_install_nightly.sh

script:
  - ./.travis_test.sh

notifications:
  email:
    - mmeyer@trobz.com